// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Intolerance struct {
	ID   pgtype.UUID
	Name string
}

type Profile struct {
	UserID   pgtype.UUID
	Username string
	Picture  pgtype.Text
	Diet     pgtype.Text
}

type ProfileIntolerance struct {
	ProfileID     pgtype.UUID
	IntoleranceID pgtype.UUID
}

type ProfileSavedRecipe struct {
	ProfileID     pgtype.UUID
	SavedRecipeID int32
}

type SavedRecipe struct {
	ID int32
}

type Security struct {
	UserID              pgtype.UUID
	SpoonacularUsername pgtype.Text
	SpoonacularHash     pgtype.Text
	SpoonacularPassword pgtype.Text
}

type User struct {
	ID           pgtype.UUID
	DisplayName  string
	Email        string
	Provider     string
	CreatedAt    pgtype.Timestamp
	LastSignInAt pgtype.Timestamp
}
