services:
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./web-client/dist:/usr/share/nginx/html
  recipe-api:
    build:
      context: ./packages/recipe
    ports:
      - "8080:8080"
    networks:
      - go-app-network

networks:
  go-app-network:
    driver: bridge
