services:
  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - bridge

  frontend:
    build: ./packages/frontend
    networks:
      - bridge

  user-service:
    build: ./packages/user
    networks:
      - bridge

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      DB_VENDOR: postgres
      DB_ADDR: user-db
      DB_DATABASE: user
      DB_USER: user
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    command: start-dev
    depends_on:
      - user-db

  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./packages/user/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
