services:
  recipe-api:
    build:
      context: ./packages/recipe
    ports:
      - "8080:8080"
    env_file:
      - "./packages/recipe/.env"

    networks:
      - go-app-network

networks:
  go-app-network:
    driver: bridge
