services:
  user-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./services/user/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

networks:
  web:
    external: true
