// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package main

import (
	"database/sql"

	"github.com/google/uuid"
)

type Intolerance struct {
	ID   uuid.UUID
	Name string
}

type Profile struct {
	UserID   uuid.UUID
	Username string
	Picture  sql.NullString
	Diet     sql.NullString
}

type ProfileIntolerance struct {
	ProfileID     uuid.UUID
	IntoleranceID uuid.UUID
}

type ProfileSavedRecipe struct {
	ProfileID     uuid.UUID
	SavedRecipeID int32
}

type SavedRecipe struct {
	ID int32
}

type Security struct {
	UserID              uuid.UUID
	SpoonacularUsername sql.NullString
	SpoonacularHash     sql.NullString
	SpoonacularPassword sql.NullString
}

type User struct {
	ID           uuid.UUID
	DisplayName  sql.NullString
	Email        string
	Provider     sql.NullString
	CreatedAt    sql.NullTime
	LastSignInAt sql.NullTime
}
