name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Docker Registry
        run: echo "${ secrets.GH_TOKEN }" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Images
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
