name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VPS_SSH_KEY }}
          known_hosts: rrat-vps

      - name: Deploy to DigitalOcean VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_NAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/capstone || exit 1
            git pull || exit 1
            make reset || exit 1
